---
- name: Install and config webserver with basic auth
  hosts: webserver
  vars_files:
    - vars/webserver_vars.yml
  tasks:
    - name: Ensure latest version of necessary package installed
      yum:
        name: 
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest
    
    - name: configure web service
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
        owner: root
        group: root
        mode: 0644

    - name: secrets dir exists
      file:
        path: "{{ secrets_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: 0500     
    - name: htpasswd file exists
      copy:
        src: "{{ secrets_src }}"
        dest: "{{ secrets_dest }}"
        owner: apache
        group: apache
        mode: 0400

    - name: ".htaccess file installed in docroot"
      copy:
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400
    - name: create index.html
      copy:
        content: "{{ ansible_facts['fqdn'] }} {{ ansible_facts['default_ipv4']['address'] }} has been customized by Ansible.\n"
        dest: "{{ web_root }}/index.html"
    - name: Firewall service enabled and started
      service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: true
    - name: open port http for the web server
      firewalld:
        service: https
        state: enabled
        immediate: true
        permanent: true
    - name: Start and enabled web server service
      service:
        name: "{{ web_svc }}"
        state: started
        enabled: true

- name: test web server qith basic auth
  hosts: localhost
  become: false
  vars:
    - web_user: guest
  vars_files:
    - vars/secret.yml
  tasks:
    - name: connect to web server with basic auth
      uri:
        url: https://serverb.lab.example.com
        validate_certs: no
        force_basic_auth: yes
        user: "{{ web_user }}"
        password: "{{ web_pass }}"
        return_content: yes
        status_code: 200
      register: auth_test

    - name: display test results
      debug:
        var: auth_test.content
