---
- name: Use the file module to remove a file
  hosts: all
  remote_user: devops
  tasks:
    - name: Remove a file from managed host
      file:
        path: /home/devops/users.txt
        state: absent
