---
- name: Enable intranet service
  hosts: servera.lab.example.com
  become: yes
  tasks:
    - name: lastest version of httpd and firewalld installed
      yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: test html page is installed
      copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html

    - name: fiewralld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permit access to httpd service
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: yes

    - name: httpd is running
      service:
        name: httpd
        state: started
        enabled: true

- name: Test intranet web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to intranet web server
      uri:
        url: http://servera.lab.example.com
        return_content: yes
        status_code: 200
...
