---
- name: Install Apache Web Server
  hosts: webserver
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python3-PyMySQL
    rule: http

  tasks:
    - name: Required packages install and update
      yum:
              name:
                      - "{{ web_pkg }}"
                      - "{{ firewall_pkg }}"
                      - "{{ python_pkg }}"
              state: latest

    - name: The {{ firewall_service }} service is started and enabled
      service:
              name: "{{ firewall_service }}"
              enabled: true
              state: started      

    - name: The web service is started and enabled
      service:
              name:  "{{ web_service }}"
              enabled: true
              state: started

    - name: Web content is in place
      copy:
              content: "Example web content" 
              dest: /var/www/html/index.html
        
    - name: The firewall port for {{ rule }} is open
      firewalld:
              service: "{{ rule }}"
              state: enabled
              permanent: true
              immediate: true

- name: Verify Apache service
  hosts: localhost
  become: false
  
  tasks:

  - name: Connect to webserver
    uri:
      url: http://servera.lab.example.com
      return_content: yes
      status_code: 200
    register: output

  - name: display output of content
    debug:
      var: output.redirected
...


