---
- name: Playbook Control Lab
  hosts: webservers
  vars_files: vars.yml
  tasks:
    #Fail Fast Message
    - name: Show failed System Requirements Message
      fail:
        msg: "The {{ inventory_hostname }} did not meet minimum reqs."
      when: >
             ansible_memtotal_mb < min_ram_mb or
             ansible_distribution != "RedHat"
    #Install all Packages
    - name: ensure required packages are present
      yum: 
        name: "{{ packages }}"
        state: latest

    #Enable and start services
    - name: Ensure services are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    #Block of config tasks
    - name: Setting up the SSL cert directory and config files
      block:
         
        - name: Create SSL cert directory
          file:
            path: "{{ ssl_cert_dir }}"
            state: directory

        - name: Coppy config Files
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ web_config_files }}"
          # this task will trigger the restart web service handler
          notify: restart web service
      #this debug task will be executed if either of two task above fail. It will print below message. 
      rescue:
        - name: Configuration Error Message
          fail:
            msg: >
              One or more of the configuration changes failed, but
              the web service is still  active.           
    #Configure the firewall
        - name: ensure web serer ports are open
          firewalld:
            service: "{{ item }}"
            state: enabled
            permanent: true
            immediate: true
          loop:
            - http
            - https

  #Add handlers
  handlers:

    - name: restart web service
      service:
        name: "{{ web_service }}"
        state: restarted

