---
- name: Reository Configuration
  hosts: all
  vars:
    custom_pkg: example-motd

  tasks:

    - name: Gather the rpm package facts
      package_facts:
        manager: auto
#This debug task will be skip if not exists custom_pkg in ansible_facts.packages
    - name: Print the rpm package facts
      debug:
        var: ansible_facts.packages[custom_pkg]
      when: custom_pkg in ansible_facts.packages

    - name: Add multiple repositories into the same file (1/2)
      yum_repository:
        name: example-internal
        description: Example INc. internal YUM repo
        file: example
        baseurl: http://materials.example.com/yum/repository/
        gpgcheck: yes
 
    - name: Ensure Repo RPM Key is Installed 
      rpm_key:
        state: present
        key: http://materials.example.com/yum/repository/RPM-GPG-KEY-example
   
    - name: Install Example motd package
      yum:
        name: "{{ custom_pkg }}"
        state: present
#Verify the custom_pkg
    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    - name: Print the rpm package facts
      debug:
        var: ansible_facts.packages[custom_pkg]
      when: custom_pkg in ansible_facts.packages


