---
- name: create user account for all our server
  hosts: devservers
  become: true
  remote_user: devops
  vars_files:
    - secret.yml
  tasks:
    - name: creating user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
