---
- name: Remove scheduled cron job
  hosts: webservers
  become: true

  tasks:
    - name: Cronjob removed
      cron:
#        name: Add date and time to a file2
        user: devops
        cron_file: add-date-time
        state: absent

